In [1]:
import numpy as np

In [4]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [5]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3d[1,0]

array([7, 8, 9])

In [8]:
arr3d.shape

(2, 2, 3)

In [9]:
arr=np.array([0,1,2,3,4,5,6,64,64,8,9])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6, 64, 64,  8,  9])

In [11]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [12]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2d[2:]

array([[7, 8, 9]])

In [16]:
arr2d[1,:2]

array([4, 5])

In [18]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2d[1:2,1:3]

array([[5, 6]])

In [23]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [24]:
data=np.random.randn(7,4)

In [25]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [26]:
data

array([[-1.08600624, -1.06184041,  0.57181071,  0.3377928 ],
       [-0.49202614,  0.40543064,  0.32514647, -0.27272384],
       [ 1.78438939, -0.16382051, -0.31118448, -0.34217015],
       [-1.13733831, -0.84602759,  0.85899475, -1.22998018],
       [ 1.09430001, -0.11385292, -0.22735448,  1.22172832],
       [-1.14778272,  0.01369067,  0.99195559, -0.123708  ],
       [-0.44591265,  1.32792455,  0.83722725, -0.4176505 ]])

In [27]:
names=='Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [28]:
data[names=='Bob']

array([[-1.08600624, -1.06184041,  0.57181071,  0.3377928 ],
       [-1.13733831, -0.84602759,  0.85899475, -1.22998018]])

In [29]:
names.dtype

dtype('<U4')

In [30]:
names.shape

(7,)

In [31]:
arr=np.empty((8,4))

In [32]:
for i in range(8):
    arr[i]=i

In [33]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [34]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [35]:
arr[[-1,-3,-4]]

array([[ 7.,  7.,  7.,  7.],
       [ 5.,  5.,  5.,  5.],
       [ 4.,  4.,  4.,  4.]])

In [37]:
arr=np.arange(15).reshape((3,5))

In [38]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [39]:
arr=np.random.randn(6,3)

In [40]:
arr

array([[ 1.32959933, -1.72142708,  0.55446462],
       [-0.33821922,  0.8437446 ,  0.44759969],
       [-0.35997982, -0.47235606,  1.08989678],
       [-0.8727581 , -2.08155612,  1.41560701],
       [ 0.81832481, -1.05510217,  1.37584141],
       [ 0.32255577,  1.17850447,  1.27346671]])

In [41]:
np.dot(arr.T,arr)

array([[  3.5472165 ,  -1.07072819,   0.49465484],
       [ -1.07072819,  10.73332564,  -3.98916242],
       [  0.49465484,  -3.98916242,   7.21425174]])

In [42]:
np.dot(arr.T,arr.T.T)

array([[  3.5472165 ,  -1.07072819,   0.49465484],
       [ -1.07072819,  10.73332564,  -3.98916242],
       [  0.49465484,  -3.98916242,   7.21425174]])

In [43]:
arr=np.arange(15).reshape((3,5))

In [44]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [45]:
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [46]:
~arr

array([[ -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10],
       [-11, -12, -13, -14, -15]], dtype=int32)

In [47]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
np.add(arr,arr)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [5]:
points=np.arange(-5,5,0.01)#1000 equally spaced points

NameError: name 'np' is not defined

In [50]:
xs,ys=np.meshgrid(points,points)

In [51]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [52]:
z=np.sqrt(xs**2+ys**2)

In [53]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [54]:
z.shape

(1000, 1000)

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt

In [4]:
plt.imshow(z,cmap=plt.cm.gray);plt.colorbar()

NameError: name 'z' is not defined

In [57]:
plt.title("Image plot of $\sqrt{x^2+y^2}$ for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2+y^2}$ for a grid of values')

In [58]:
plt.show

<function matplotlib.pyplot.show>

In [61]:
plt.imshow(z,cmap=plt.cm.gray)

In [62]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [63]:
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [64]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [65]:
values=np.array([6,0,0,3,2,5,6])

In [66]:
np.in1d(values,[2,3,5])

array([False, False, False,  True,  True,  True, False], dtype=bool)

In [67]:
arr=np.arange(16).reshape((2,2,4))

In [68]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [69]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [70]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [75]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = Series([4,7,5,-3])

In [4]:
obj

0    4
1    7
2    5
3   -3
dtype: int64

In [5]:
obj.values

array([ 4,  7,  5, -3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2=Series([4,7,5,-3],index=['d','b','c','a'])

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2

d    4
b    7
c    5
a   -3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'c', 'a'], dtype='object')

In [11]:
obj2[obj2>0]

d    4
b    7
c    5
dtype: int64

In [12]:
obj2*2

d     8
b    14
c    10
a    -6
dtype: int64

In [13]:
import numpy as np

In [14]:
np.exp(obj2)

d      54.598150
b    1096.633158
c     148.413159
a       0.049787
dtype: float64

In [15]:
sdata={'ohio':35000,'texas':71000,'oregon':16000,'Utah':5000}

In [16]:
states=['California','ohio','oregon','texas']

In [17]:
obj4=Series(sdata,states)

In [18]:
obj4

California        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [19]:
obj3=Series(sdata)

In [20]:
obj3

Utah       5000
ohio      35000
oregon    16000
texas     71000
dtype: int64

In [21]:
obj3+obj4

California         NaN
Utah               NaN
ohio           70000.0
oregon         32000.0
texas         142000.0
dtype: float64

In [22]:
obj4+obj3

California         NaN
Utah               NaN
ohio           70000.0
oregon         32000.0
texas         142000.0
dtype: float64

In [23]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
     'year':[2000,2001,2002,2001,2002,2003],
     'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=DataFrame(data)

In [25]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [27]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [29]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [30]:
frame2=DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])

In [31]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [32]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [33]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [34]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [35]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [37]:
frame2['debt']=165

In [39]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   165
two    2001    Ohio  1.7   165
three  2002    Ohio  3.6   165
four   2001  Nevada  2.4   165
five   2002  Nevada  2.9   165
six    2003  Nevada  3.2   165

In [41]:
frame2['debt']=np.arange(6.)

In [54]:
frame2['debt']=range(0,6)

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [51]:
list(a)

[0, 1, 2, 3, 4, 5]

In [53]:
a

range(0, 6)

In [1]:
import pandas as pd

In [2]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [3]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj2=obj.reindex(['a','b','c','d'])

In [5]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [6]:
import numpy as np

In [7]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [8]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [9]:
new_obj=obj.drop('c')

In [10]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [12]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=['ohio','colorado','utah','new york'],columns=['one','two','three','four'])

In [13]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [14]:
data.drop(['colorado','ohio'])

one  two  three  four
utah        8    9     10    11
new york   12   13     14    15

In [15]:
data.drop('two',axis=1)

one  three  four
ohio        0      2     3
colorado    4      6     7
utah        8     10    11
new york   12     14    15

In [17]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])

In [18]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [19]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [22]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=['ohio','colorado','utah','new york'],columns=['one','two','three','four'])
print(data)

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15


In [21]:
print(data)

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15


In [24]:
data['two']

ohio         1
colorado     5
utah         9
new york    13
Name: two, dtype: int32

In [25]:
data[:2]

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7

In [26]:
data[data['three']>5]

one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [27]:
data.loc['colorado',['two','one']]

two    5
one    4
Name: colorado, dtype: int32

In [28]:
data.iloc[:,:3][data.three>5]

one  two  three
colorado    4    5      6
utah        8    9     10
new york   12   13     14

In [29]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [30]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [31]:
df2.loc[1,'b']=np.nan

In [32]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [33]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [34]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [35]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0